import type { ChoFs } from "../cho-fs.ts";

// Make Deno available as Cho in the global scope
export const DenoFs: ChoFs = {
  chmod: Deno.chmod,
  chown: Deno.chown,
  copyFile: Deno.copyFile,
  copyFileSync: Deno.copyFileSync,
  create: Deno.create,
  createSync: Deno.createSync,
  link: Deno.link,
  linkSync: Deno.linkSync,
  lstat: Deno.lstat,
  lstatSync: Deno.lstatSync,
  makeTempDir: Deno.makeTempDir,
  makeTempDirSync: Deno.makeTempDirSync,
  makeTempFile: Deno.makeTempFile,
  makeTempFileSync: Deno.makeTempFileSync,
  mkdir: Deno.mkdir,
  mkdirSync: Deno.mkdirSync,
  open: Deno.open,
  openSync: Deno.openSync,
  readDir: Deno.readDir,
  readDirSync: Deno.readDirSync,
  readFile: Deno.readFile,
  readFileSync: Deno.readFileSync,
  remove: Deno.remove,
  removeSync: Deno.removeSync,
  rename: Deno.rename,
  renameSync: Deno.renameSync,
  stat: Deno.stat,
  statSync: Deno.statSync,
  symlink: Deno.symlink,
  symlinkSync: Deno.symlinkSync,
  truncate: Deno.truncate,
  truncateSync: Deno.truncateSync,
  writeFile: Deno.writeFile,
  writeFileSync: Deno.write,
};
