name: Publish
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.0.0 or major/minor/patch)'
        required: true
      lib:
        description: 'Library to publish (core or web)'
        required: true
#  push:
#    branches:
#      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup version
        run: |
          ./scripts/next.sh ${{ github.event.inputs.lib }}/jsr.json ${{ github.event.inputs.version }}

      - name: publish
        run: |
          cd ${{ github.event.inputs.lib }}
          npx jsr publish --allow-dirty
